/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

#include <iostream>

void recurse(int val1, int val2) {
    static int sum = 0;

    int term = val1 + val2;
    if (term <= 4000000) {
        if (term % 2 == 0) {
            sum += term;
        }
        recurse(val2, term);
    } else {
        std::cout << sum << std::endl;
    }
}

int main(int argc, char* argv[]) {
    recurse(1, 1);

    return 0;
}
